services:
  schedora.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123456
    ports:
      - "5280:8080"
      - "5281:8081"
    volumes:
      - ~/.aspnet/https:/https
    networks:
      - backend
    depends_on:
      - sqlserver
      - rabbitMq
      - redis
  
  redis:
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data


  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    platform: linux/amd64
    container_name: sqlserver
    ports:
      - 1433:1433
    restart: always
    volumes: 
     - sqlserver_data:/var/opt/mssql
    networks:
     - backend
    environment:
     - MSSQL_SA_PASSWORD=hG5rzck2vy3cHai
     - ACCEPT_EULA=Y

networks:
  backend:
    driver: bridge

volumes:
  sqlserver_data:
  redis_data: