services:
  schedora.webapi:
    image: ${DOCKER_REGISTRY-}schedorawebapi
    build:
      context: .
      dockerfile: src/backend/Schedora.WebApi/Dockerfile
      
  rabbitMq:
    container_name: "rabbit_mq"
    image: rabbitmq:3-management
    networks:
      - backend
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    container_name: redis
    image: redis:latest
    networks:
      - backend
  
