# This is a generated file. Not intended for manual editing.
services:
  schedora.webapi:
    build:
      context: "/Users/henrique/Projects/SchedoraSocialMediaScheduler"
      dockerfile: "src/backend/Schedora.WebApi/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Schedora.WebApi.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "schedorawebapi:dev"
    ports: []
    volumes:
    - "/Users/henrique/Projects/SchedoraSocialMediaScheduler/src/backend/Schedora.WebApi:/app:rw"
    - "/Users/henrique/Projects/SchedoraSocialMediaScheduler:/src:rw"
    - "/Users/henrique/.nuget/packages:/home/app/.nuget/packages"
    working_dir: "/app"
