# This is a generated file. Not intended for manual editing.
services:
  schedora.webapi:
    build:
      context: "/Users/henrique/Projects/SchedoraSocialMediaScheduler"
      dockerfile: "src/backend/Schedora.WebApi/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-arm64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57403"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "schedorawebapi:dev"
    ports:
    - "127.0.0.1:57003:57000"
    - "127.0.0.1:57203:57200"
    - "127.0.0.1:57403:57403"
    volumes:
    - "/Users/henrique/Projects/SchedoraSocialMediaScheduler/src/backend/Schedora.WebApi:/app:rw"
    - "/Users/henrique/Projects/SchedoraSocialMediaScheduler:/src:rw"
    - "/Users/henrique/.nuget/packages:/home/app/.nuget/packages"
    - "/Users/henrique/.local/share/JetBrains/RiderRemoteDebugger/2025.3.0.3/LinuxArm64:/opt/JetBrains/RiderDebuggerTools"
    - "/Applications/Rider.app/Contents/bin/backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "/Users/henrique/Library/Logs/JetBrains/Rider2025.3/DebuggerWorker/JetBrains.Debugger.Worker.2025_12_03_15_30_06:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
